name: Mirror to Gitee Repo

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '05 14 * * *'


jobs:
  git-mirror:
    runs-on: ubuntu-20.04
    steps:
      - name: Configure Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CHNCAESAR_SECRET }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Push Mirror
        env:
          SOURCE_REPO: 'https://github.com/chncaesar/hive-lineage-hook'
          DESTINATION_REPO: 'git@github.com:chncaesar/hive_lineage_hook_mirror.git'
        run: |
          git clone --mirror "$SOURCE_REPO" && cd `basename "$SOURCE_REPO"`
          git remote set-url --push origin "$DESTINATION_REPO"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
